### ISSUE TITLE
 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by shluh** [lucascs94/prova_4all#1]
Boa tarde. Por gentileza verificar a exceção abaixo, pois não está sendo possível rodar os testes desenvolvidos.

Cenario: Realizar compra corretamente                       # /prova_4all/src/main/java/features/RealizarCompraCorretamente.feature:4
      java.lang.IllegalStateException: **The driver is not executable**: /prova_4all/configuration/drivers/chromedriver.exe
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:150)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:141)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:159)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:94)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at utils.DriverFactory.getDriver(DriverFactory.java:18)
	at setup.TestRule.configuraTeste(TestRule.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:65)
	at cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.TestCase.run(TestCase.java:42)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at cucumber.api.cli.Main.run(Main.java:28)
	at cucumber.api.cli.Main.main(Main.java:15)

**Comment by shluh** [comment]
Se possivel fazer o tratamento de finalização  do driver, para nao retornar igual como abaixo:



Finalizando estância do chromeDriver
      java.lang.NullPointerException

**Comment by shluh** [comment]
Ajustado driver para ambiente linux
