### ISSUE TITLE
Exception in thread "main" cucumber.runtime.CucumberException: Failed to parse resource at: 

### ISSUE THREAD

**Issue by shluh** [lucascs94/prova_4all#2]
### Gentileza verificar a exceção abaixo ao rodar os testes:
(**Porfavor, fechar a Issue ao ajustar o código**)

Exception in thread "main" cucumber.runtime.CucumberException: **Failed to parse resource a**t: file:prova_4all/src/test/java/ui/RealizarCompraCorretamente.java
    at cucumber.runtime.model.FeatureParser.parseResource(FeatureParser.java:40)
    at cucumber.runtime.model.FeatureBuilder.parse(FeatureBuilder.java:25)
    at cucumber.runtime.model.FeatureLoader.loadFromFeaturePath(FeatureLoader.java:36)
    at cucumber.runtime.model.FeatureLoader.load(FeatureLoader.java:23)
    at cucumber.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:33)
    at cucumber.runtime.Runtime.run(Runtime.java:78)
    at io.cucumber.core.cli.Main.run(Main.java:43)
    at cucumber.api.cli.Main.run(Main.java:28)
    at cucumber.api.cli.Main.main(Main.java:15)
**Caused by: gherkin.ParserException$CompositeParserException: Parser errors:**
(1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'package ui;'
(3:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'import io.cucumber.junit.Cucumber;'
(4:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'import io.cucumber.junit.CucumberOptions;'
(5:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'import org.junit.runner.RunWith;'
(9:9): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'glue = { "" }, monochrome = true, junit = "--step-notifications")'
(10:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'public class RealizarCompraCorretamente {'
(12:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '}'
(13:0): **unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty**
    at gherkin.Parser.parse(Parser.java:143)
    at gherkin.Parser.parse(Parser.java:118)
    at gherkin.Parser.parse(Parser.java:114)
    at cucumber.runtime.model.FeatureParser.parseResource(FeatureParser.java:36)
    ... 8 more

**Comment by shluh** [comment]
Fechar esta issue junto ao commit
